### PR TITLE
Permit

### LINKED ISSUE #304: Fetch Permit Nonce
### Description

Write and test a function to test the permit nonce.

```
public async fetchPermitNonce(
    address: string,
    mediaId: BigNumberish
  ): Promise<BigNumber> {
    return this.media.permitNonces(address, mediaId)
  }
```

### Definition of Done

The function passes the test and is merged to the current changes.

### LINKED ISSUE #314: permit
### Descritpion

Write and test a function that approves meta transactions as outlined in [EIP-712](https://eips.ethereum.org/EIPS/eip-712#abstract)

```
 /**
   * Grants the spender approval for the specified media using meta transactions as outlined in EIP-712
   * @param sender
   * @param mediaId
   * @param sig
   */
  public async permit(
    spender: string,
    mediaId: BigNumberish,
    sig: EIP712Signature
  ): Promise<ContractTransaction> {
    try {
      this.ensureNotReadOnly()
    } catch (err) {
      return Promise.reject(err.message)
    }

    return this.media.permit(spender, mediaId, sig)
  }

```

### Definition of Done

Hash approval is successful.

### PR DESCRIPTION
**Pull request by jpkim921**
## Summary

Closes #314

## Implementation
- [x]  Add fetchPermitNonce()
- [x]  Add permit()
    - [x] Add private method `ensureNotReadOnly`.
    - [x] Add helper method `eip712Domain`.
- [x]  Test `permit`
- [ ]  Test ``fetchPermitNonce`. 

## Files
```sdk/nft/src/types.ts```
```sdk/nft/src/zapMedia.ts```
```sdk/nft/test/zapMedia.test.ts```

### CODE REVIEW

**Comment by jungsNN** [comment]
```

1 failing

  1) ZapMedia
       Contract Functions
         View Functions
           test fetchContentHash, fetchMetadataHash, fetchPermitNonce
             Should be able to fetch permitNonce:
     Error: processing response error (body="{\"id\":128,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert Media: Signature invalid\",\"code\":-32000,\"data\":{\"stack\":\"c: VM Exception while processing transaction: revert Media: Signature invalid\\n    at Function.c.fromResults (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\\n    at e.exports (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)\",\"name\":\"c\"}}}", error={"code":-32000,"data":{"stack":"c: VM Exception while processing transaction: revert Media: Signature invalid\n    at Function.c.fromResults (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\n    at e.exports (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)","name":"c"}}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x060c798db266961765a1978fe8d5321bbb266b4e\",\"to\":\"0x04cb55958af41f727be050e38ae2fa8adf85e2d5\",\"data\":\"0x0e2a17780000000000000000000000007e2ba56fcf8d826ab8a4b08e60ef9e1a32e6849300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000061e20262000000000000000000000000000000000000000000000000000000000000001bae91f954e4fe3335ab16e12a1d236b7c86984f08d3117a5b10d54aabe464ce69062fc481e0ce9dfedffa645fc4556745c79f83c2b7133f1a577338d619a5eb3f\"}],\"id\":128,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.5.1)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at /Users/jennyjung/Development/Zap/hardhat/zdkbsc/sdk/nft/node_modules/@ethersproject/web/src.ts/index.ts:321:28
      at step (node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      
      ```

**Comment by jpkim921** [comment]
ill follow up with @jungsNN. 
That test shouldn't even run since i added a .skip to it.

**Comment by Kaleb47** [comment]
I'll check it out tomorrow!

**Comment by Kaleb47** [comment]
> ```
> 
> 1 failing
> 
>   1) ZapMedia
>        Contract Functions
>          View Functions
>            test fetchContentHash, fetchMetadataHash, fetchPermitNonce
>              Should be able to fetch permitNonce:
>      Error: processing response error (body="{\"id\":128,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert Media: Signature invalid\",\"code\":-32000,\"data\":{\"stack\":\"c: VM Exception while processing transaction: revert Media: Signature invalid\\n    at Function.c.fromResults (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\\n    at e.exports (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)\",\"name\":\"c\"}}}", error={"code":-32000,"data":{"stack":"c: VM Exception while processing transaction: revert Media: Signature invalid\n    at Function.c.fromResults (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\n    at e.exports (/Users/jennyjung/.npm/_npx/3c384932ee54bc40/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)","name":"c"}}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x060c798db266961765a1978fe8d5321bbb266b4e\",\"to\":\"0x04cb55958af41f727be050e38ae2fa8adf85e2d5\",\"data\":\"0x0e2a17780000000000000000000000007e2ba56fcf8d826ab8a4b08e60ef9e1a32e6849300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000061e20262000000000000000000000000000000000000000000000000000000000000001bae91f954e4fe3335ab16e12a1d236b7c86984f08d3117a5b10d54aabe464ce69062fc481e0ce9dfedffa645fc4556745c79f83c2b7133f1a577338d619a5eb3f\"}],\"id\":128,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8545", code=SERVER_ERROR, version=web/5.5.1)
>       at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
>       at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
>       at /Users/jennyjung/Development/Zap/hardhat/zdkbsc/sdk/nft/node_modules/@ethersproject/web/src.ts/index.ts:321:28
>       at step (node_modules/@ethersproject/web/lib/index.js:33:23)
>       at Object.next (node_modules/@ethersproject/web/lib/index.js:14:53)
>       at fulfilled (node_modules/@ethersproject/web/lib/index.js:5:58)
>       at processTicksAndRejections (node:internal/process/task_queues:96:5)
>       
>       ```
> ```

Yes this happened on my machine as well!

**Comment by jpkim921** [comment]
i need to take out/change readonly function in zapMedia.ts

**Pull request merged**
